version: '3'
services:
  backend:
    build: .
    depends_on:
      - db
      - redis
    restart: always
    env_file:
      - s3.env
    environment:
      DB_USERNAME: user
      DB_PASSWORD: mysecret
      DB_HOST: db
      REDIS_HOST: redis
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: video
  frontend:
    image: nginx:1.21
    volumes:
      - ./simple-frontend:/usr/share/nginx/html
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - backend
  redis:
    image: redis:7
