version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    env_file:
      - s3.env
    environment:
      DB_USERNAME: user
      DB_PASSWORD: mysecret
      DB_HOST: db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: video
